# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  # boxes at https://app.vagrantup.com/ubuntu/boxes/trusty64
  config.vm.box = "ubuntu/trusty64"

  # Box setting
  config.vm.box_check_update = false
  config.vbguest.auto_update = false

  # Network setting
  config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1", auto_connect:true
  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"

  # folder setteing
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider setting
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
    vb.check_guest_additions = false
    vb.name = "box_name_1"
    # Customize the amount of memory and cpu on the VM:
    vb.memory = 2048
    vb.cpus = 2
  end
   
  # Provision setting
  config.vm.provision "shell", path: "vagrant.sh"
  # config.vm.provision "shell" do |shell|
  #   shell.path = "C:/Users/SIMPLON/Documents/SIMPLON/Formation_AWS/Devoirs/Vagrant/lab_1/vagrant.sh"
  # end
  # config.vm.provision "shell", inline: <<-SHELL
  #  apt-get update
  #   apt-get install -y apache2
  # SHELL
end
