# -*- mode: ruby -*-
# vi: set ft=ruby :

GUI = false
BOX_NAME = "Box_Name"
BOX_HOSTNAME = "box_Hostname"
BOX_RAM = 2048
BOX_CPU = 2
BOX_DISK = 50

Vagrant.configure("2") do |config|
  config.vm.box = "base"
  config.vm.box_url = "https://cloud-images.ubuntu.com/bionic/20230315/bionic-server-cloudimg-amd64-vagrant.box"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = GUI
    vb.name = BOX_NAME
    vb.memory = BOX_RAM
    vb.cpus = BOX_CPU
  end
end
