# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"

  config.vm.box_check_update = false

  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.check_guest_additions = false
    vb.name = "VM_docker_init"
    vb.memory = 2048
    vb.cpus = 2
  end
  config.vm.provision "shell", path: "run.sh"
end
